# Generated by Django 5.0.3 on 2024-03-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_eventorganizer_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='user',
        ),
        migrations.AddField(
            model_name='attendee',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
            preserve_default=False,
        ),
    ]
