# Generated by Django 5.0.3 on 2024-03-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_attendee_user_attendee_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='profile',
            new_name='eventOrganizer',
        ),
    ]
