# Generated by Django 5.0.3 on 2024-03-30 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events',
        ),
        migrations.AddField(
            model_name='attendee',
            name='events',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
