# Generated by Django 5.0.3 on 2024-03-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_attendee_events_attendee_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='eventOrganizer',
            new_name='attendee',
        ),
    ]
