# Generated by Django 5.0.3 on 2024-03-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_eventorganizer_attendee_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLikers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventLiked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('likers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
