# Generated by Django 5.0.3 on 2024-03-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_organizerapplicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizerApplicant',
        ),
    ]
