# Generated by Django 5.0.3 on 2024-04-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_nonorganizerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
