# Generated by Django 5.0.3 on 2024-04-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_event_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonOrganizerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(null=True)),
                ('eventVenue', models.TextField(null=True)),
                ('eventDate', models.DateField()),
                ('eventDescription', models.TextField(null=True)),
                ('eventNumberOfAttendees', models.IntegerField(default=0)),
                ('eventLikes', models.IntegerField(default=0)),
                ('eventOrganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_organizer_events_organized', to='api.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_organizer_events', to='api.userprofile')),
            ],
        ),
    ]
