# Generated by Django 5.0.3 on 2024-04-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_nonorganizerevent_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', through='api.Attendee', to='api.userprofile'),
        ),
    ]
